services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    volumes:
      - ./auth_info:/app/auth_info
    restart: unless-stopped
    stdin_open: true # Equivalente a -i (interactivo)
    tty: true        # Equivalente a -t (tty), necesario para qrcode-terminal
